# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-12 12:54
from __future__ import unicode_literals

import GroundSegment.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
                ('dtArrival', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo del estado de la alarma', max_length=24, unique=True, verbose_name='Codigo del estado de la alarma')),
                ('description', models.CharField(help_text='Decripcion del estado de la alarma', max_length=100, unique=True, verbose_name='Decripcion del estado de la alarma')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo del satelite, ejemplo FS2017', max_length=24, unique=True, verbose_name='Codigo del tipo de alarma')),
                ('description', models.CharField(help_text='Decripcion del satelite', max_length=100, unique=True, verbose_name='Decripcion del tipo de alarma')),
                ('procedure', models.TextField(help_text='Procedimiento a ejecutar por los ingenieros de vuelo en caso de ocurrir alarma', max_length=512)),
                ('timeout', models.IntegerField(help_text='tiempo maximo para tratar la alarma', verbose_name='Tiempo maximo para tratar la alarma')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmTypeNotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarmType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AlarmTypeNotificationTypes', to='GroundSegment.AlarmType')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del contacto', max_length=64, unique=True, verbose_name='Nombre del contacto')),
                ('email', models.EmailField(max_length=512, verbose_name='EMail del contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True, verbose_name='Codigo del Pais')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Nombre del Pais')),
                ('description', models.CharField(max_length=24, unique=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Criticity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo del satelite, ejemplo FS2017', max_length=24, unique=True, verbose_name='Codigo de criticidad')),
                ('description', models.CharField(help_text='Decripcion del satelite', max_length=100, unique=True, verbose_name='Decripcion de la criticidad')),
                ('color', models.CharField(default='#FF0000', max_length=7)),
                ('sound', models.FileField(upload_to='', verbose_name='/media')),
            ],
            options={
                'verbose_name': 'Criticidad',
                'verbose_name_plural': 'Criticidades',
            },
        ),
        migrations.CreateModel(
            name='DCPData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataTime', models.DateTimeField(auto_now_add=True)),
                ('receive_dataTime', models.DateTimeField(auto_now_add=True)),
                ('Precipitation', models.FloatField(default=0.0, help_text='Precipitacion_Totalizador')),
                ('Humidity', models.FloatField(default=0.0, help_text='Humedad [%]')),
                ('Atm_preasure', models.FloatField(default=0.0, help_text='Presion Atmosferica [%]')),
                ('Temp_max', models.FloatField(default=0.0, help_text='Temperatura maxima [C]')),
                ('Temp_media', models.FloatField(default=0.0, help_text='Temperatura media [C]')),
                ('Temp_min', models.FloatField(default=0.0, help_text='Temperatura minima [C]')),
            ],
        ),
        migrations.CreateModel(
            name='DCPPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True, verbose_name='Codigo de la Plataforma')),
                ('type', models.CharField(max_length=24, null=True, verbose_name='Tipo de Plataforma')),
                ('equip_marca', models.CharField(default='no conocido', max_length=24, null=True, verbose_name='Marca del Equipo')),
                ('equip_model', models.CharField(default='no conocido', max_length=24, null=True, verbose_name='Modelo del Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='DownlinkFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frameCommand', models.IntegerField(help_text='frame Command', verbose_name='frame Command')),
                ('frameLength', models.IntegerField(help_text='Dimension del frame', verbose_name='Dimension del frame')),
                ('dataRate', models.IntegerField(help_text='Tasa de transferencia', verbose_name='Tasa de transferencia')),
                ('modulationName', models.CharField(help_text='Nombre de la modulacion', max_length=24, verbose_name='Nombre de la modulacion')),
                ('rssi', models.FloatField(help_text='RSSI')),
                ('frequency', models.FloatField(help_text='Frecuencia')),
                ('packetLength', models.IntegerField(help_text='Dimension del paquete', verbose_name='Dimension del paquete')),
                ('ax25Destination', models.CharField(help_text='ax25 destination value', max_length=16, null=True, verbose_name='ax25 destination value')),
                ('ax25Source', models.CharField(help_text='ax25 Source value', max_length=16, null=True, verbose_name='ax25 Source value')),
                ('ax25Protocol', models.CharField(help_text='ax25 Protocol value', max_length=16, null=True, verbose_name='ax25 Protocol value')),
                ('ax25Control', models.CharField(help_text='ax25 Control value', max_length=16, null=True, verbose_name='ax25 Control value')),
                ('packetNumber', models.IntegerField(default=0)),
                ('frameTypeId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Eclipse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('stopTime', models.DateTimeField()),
                ('duration', models.FloatField(default=0.0, help_text='[minutos]', verbose_name='Duracion')),
                ('tleDistance', models.FloatField(default=0, verbose_name='Fraccion de dias de distancia al TLE ')),
                ('obsolete', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo', max_length=24, verbose_name='Codigo del tipo de log')),
                ('description', models.TextField(help_text='Decripcion del log', max_length=512, verbose_name='Decripcion log')),
                ('module', models.CharField(help_text='Modulo que genera el log', max_length=64, verbose_name='Modulo')),
                ('logType', models.IntegerField(choices=[(0, 'Information'), (1, 'Warning'), (2, 'Error')], default=0, verbose_name='Tipo de log')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='sin nombre', help_text='Nombre de la plantilla', max_length=64, unique=True, verbose_name='Nombre de la plantilla')),
                ('subject', models.CharField(default='sin nombre', help_text='Asunto del mensaje', max_length=64, unique=True, verbose_name='Asunto del mensaje')),
                ('text', models.TextField(default='Sin mensaje')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='subject default', help_text='Asunto de la notificacion', max_length=128, verbose_name='Asunto de la notificacion')),
                ('text', models.TextField(default='Sin mensaje')),
                ('sended', models.BooleanField(default=False)),
                ('ntry', models.IntegerField(default=0)),
                ('alarmTypeNotificationType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='GroundSegment.AlarmTypeNotificationType')),
                ('contacts', models.ManyToManyField(related_name='notifications', to='GroundSegment.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo del tipo de notificacion', max_length=64, unique=True, verbose_name='Codigo del tipo de notificacion')),
                ('description', models.CharField(help_text='Decripcion del tipo de notificacion', max_length=128, unique=True, verbose_name='Decripcion del tipo de Notificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text='Modulo donde normalmente se usuario el parametro', max_length=64, verbose_name='Modulo')),
                ('key', models.CharField(help_text='Clave', max_length=24, verbose_name='Clave')),
                ('value', models.CharField(help_text='Valor del parametro', max_length=128, verbose_name='Valor')),
                ('description', models.TextField(default='Describir parametro aqui', help_text='Descripcion del parametro, donde se usa, para que?', verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Pasada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('stopTime', models.DateTimeField()),
                ('duration', models.FloatField(default=0.0, help_text='[minutos]', verbose_name='Duracion')),
            ],
        ),
        migrations.CreateModel(
            name='PassGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('day', models.DateField(verbose_name='Fecha que se toma en consideracion')),
            ],
        ),
        migrations.CreateModel(
            name='Propagation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('final', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropagationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dt', models.DateTimeField()),
                ('positionX', models.FloatField()),
                ('positionY', models.FloatField()),
                ('positionZ', models.FloatField()),
                ('velocityX', models.FloatField()),
                ('velocityY', models.FloatField()),
                ('velocityZ', models.FloatField()),
                ('earthDistance', models.FloatField(default=0.0)),
                ('propagation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagationDetails', to='GroundSegment.Propagation')),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo del satelite, ejemplo FS2017', max_length=24, unique=True, verbose_name='Codigo del satelite')),
                ('description', models.CharField(help_text='Decripcion del satelite', max_length=100, unique=True, verbose_name='Decripcion del satelite')),
                ('noradId', models.IntegerField(help_text='Codigo norad del satelite', unique=True, verbose_name='Codigo norad del satelite')),
                ('active', models.BooleanField(default=True, verbose_name='Activacion/desactivacion del satelite')),
                ('notes', models.TextField(max_length=512, null=True, verbose_name='Observaciones sobre el satelite')),
                ('inContact', models.BooleanField(default=False, verbose_name='Si el satelite esta con enlace activo')),
                ('commServerIP', models.CharField(default='127.0.0.1', help_text='IP servidor/cortex', max_length=24, verbose_name='IP servidor/cortex ')),
                ('commServerPort', models.CharField(default='3210', help_text='Puerto servidor/cortex', max_length=24, verbose_name='Puerto servidor/cortex')),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo de estado del satelite', max_length=24, unique=True, verbose_name='Codigo de estado')),
                ('description', models.CharField(help_text='Decripcion del estado del satelite', max_length=100, unique=True, verbose_name='Codigo de estado')),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Nombre del Sitio')),
                ('lat', models.FloatField(help_text='[Dato en Grados Decimales]', validators=[GroundSegment.validators.validate_lat], verbose_name='Latitud')),
                ('lon', models.FloatField(help_text='[Grados Decimales]', verbose_name='Longitud')),
                ('h', models.FloatField(help_text='[metros]', verbose_name='Altura')),
                ('maskElev', models.FloatField(default=0.0, help_text='[grados]', verbose_name='Mascara de Elevacion')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True, verbose_name='Codigo del Estado')),
                ('name', models.CharField(max_length=24, verbose_name='Nombre del Estado')),
                ('description', models.CharField(max_length=24, verbose_name='Descripcion')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='GroundSegment.Country')),
            ],
        ),
        migrations.CreateModel(
            name='SubSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo del subsistema', max_length=24, unique=True, verbose_name='Codigo del subsistema')),
                ('description', models.CharField(help_text='Decripcion del subsistema', max_length=100, unique=True, verbose_name='Decripcion del subsistema')),
            ],
        ),
        migrations.CreateModel(
            name='Tle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tleDateTime', models.DateTimeField(auto_now_add=True)),
                ('downloaded', models.DateTimeField(auto_now_add=True)),
                ('lines', models.TextField(max_length=124)),
                ('epoch', models.DateTimeField(null=True, verbose_name='Epoca del TLE')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tles', to='GroundSegment.Satellite')),
            ],
            options={
                'get_latest_by': 'tleDateTime',
            },
        ),
        migrations.CreateModel(
            name='TrackPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('pasada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackPoints', to='GroundSegment.Pasada')),
            ],
        ),
        migrations.CreateModel(
            name='Watchdog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo', max_length=24, verbose_name='Codigo del watchdog')),
                ('description', models.TextField(help_text='Decripcion del watchdog', max_length=512, verbose_name='Decripcion watchdog')),
                ('module', models.CharField(help_text='Modulo que genera actualiza el watchdog', max_length=64, verbose_name='Modulo')),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
                ('tolerance', models.FloatField(verbose_name='Tiempo de tolerancia')),
            ],
        ),
        migrations.AddField(
            model_name='sitio',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitios', to='GroundSegment.State'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellites', to='GroundSegment.SatelliteState'),
        ),
        migrations.AddField(
            model_name='propagation',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagations', to='GroundSegment.Satellite'),
        ),
        migrations.AddField(
            model_name='propagation',
            name='tle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagations', to='GroundSegment.Tle'),
        ),
        migrations.AddField(
            model_name='passgeneration',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passGenerations', to='GroundSegment.Satellite'),
        ),
        migrations.AddField(
            model_name='passgeneration',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passGenerations', to='GroundSegment.Sitio'),
        ),
        migrations.AddField(
            model_name='passgeneration',
            name='tle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passGenerations', to='GroundSegment.Tle'),
        ),
        migrations.AddField(
            model_name='pasada',
            name='passGeneration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='GroundSegment.PassGeneration'),
        ),
        migrations.AddField(
            model_name='pasada',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasadas', to='GroundSegment.Satellite'),
        ),
        migrations.AddField(
            model_name='pasada',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasadas', to='GroundSegment.Sitio'),
        ),
        migrations.AddField(
            model_name='pasada',
            name='tle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasadas', to='GroundSegment.Tle'),
        ),
        migrations.AddField(
            model_name='eclipse',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eclipses', to='GroundSegment.Satellite'),
        ),
        migrations.AddField(
            model_name='eclipse',
            name='tle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eclipses', to='GroundSegment.Tle'),
        ),
        migrations.AddField(
            model_name='downlinkframe',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloadlinkFrames', to='GroundSegment.Satellite'),
        ),
        migrations.AddField(
            model_name='dcpplatform',
            name='sitio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcpplatform', to='GroundSegment.Sitio'),
        ),
        migrations.AddField(
            model_name='dcpdata',
            name='dcp_plataform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcpdatas', to='GroundSegment.DCPPlatform'),
        ),
        migrations.AddField(
            model_name='alarmtypenotificationtype',
            name='contacts',
            field=models.ManyToManyField(related_name='alarmTypeNotificationType', to='GroundSegment.Contact'),
        ),
        migrations.AddField(
            model_name='alarmtypenotificationtype',
            name='messageTemplate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AlarmTypeNotificationTypes', to='GroundSegment.MessageTemplate'),
        ),
        migrations.AddField(
            model_name='alarmtypenotificationtype',
            name='notificationType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AlarmTypeNotificationTypes', to='GroundSegment.NotificationType'),
        ),
        migrations.AddField(
            model_name='alarmtype',
            name='criticity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarmstype', to='GroundSegment.Criticity'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='alarmType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='GroundSegment.AlarmType'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='GroundSegment.Satellite'),
        ),
    ]
