# Generated by Django 2.0.7 on 2018-11-20 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='alarmType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarms', to='GroundSegment.AlarmType'),
        ),
        migrations.AlterField(
            model_name='alarmtype',
            name='criticity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarmstype', to='GroundSegment.Criticity'),
        ),
        migrations.AlterField(
            model_name='dcpdata',
            name='dcp_plataform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dcpdatas', to='GroundSegment.DCPPlatform'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='contacts',
            field=models.ManyToManyField(limit_choices_to=100, related_name='notifications', to='GroundSegment.Contact'),
        ),
        migrations.AlterField(
            model_name='passgeneration',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passGenerations', to='GroundSegment.Satellite'),
        ),
        migrations.AlterField(
            model_name='passgeneration',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passGenerations', to='GroundSegment.Sitio'),
        ),
        migrations.AlterField(
            model_name='passgeneration',
            name='tle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passGenerations', to='GroundSegment.Tle'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propagations', to='GroundSegment.Satellite'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='tle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propagations', to='GroundSegment.Tle'),
        ),
        migrations.AlterField(
            model_name='propagationdetail',
            name='propagation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propagationDetails', to='GroundSegment.Propagation'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satellites', to='GroundSegment.SatelliteState'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sitios', to='GroundSegment.State'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='GroundSegment.Country'),
        ),
        migrations.AlterField(
            model_name='tle',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tles', to='GroundSegment.Satellite'),
        ),
    ]
