# Generated by Django 2.2.1 on 2019-05-21 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0002_auto_20181120_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propagationdetail',
            name='propagation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagationDetails', to='GroundSegment.Propagation'),
        ),
    ]
