# Generated by Django 2.2.2 on 2020-03-10 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0037_auto_20200304_1335'),
        ('GroundSegment', '0004_auto_20190528_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='extractDateTimeFun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='satellites', to='Telemetry.Calibration'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='satnogs',
            field=models.BooleanField(default=False, verbose_name='Satelite incorporado a satnogs'),
        ),
    ]
