# Generated by Django 2.2.2 on 2020-03-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0039_tlmyvartype_frametype'),
        ('GroundSegment', '0005_auto_20200310_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='extractFrameTypeFun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extract_frametype_satellites', to='Telemetry.Calibration'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='extractDateTimeFun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extract_datetime_satellites', to='Telemetry.Calibration'),
        ),
    ]
