# Generated by Django 2.2 on 2019-05-16 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GroundSegment', '0002_auto_20181120_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo del sistema de referencia', max_length=24, unique=True, verbose_name='Codigo del sistema de referencia')),
                ('description', models.CharField(help_text='Descripcion  del sistema de referencia', max_length=100, unique=True, verbose_name='Decripcion del sistema de referencia')),
            ],
        ),
        migrations.CreateModel(
            name='Ephem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0, help_text='vector posicion X')),
                ('y', models.FloatField(default=0.0, help_text='vector posicion Y')),
                ('z', models.FloatField(default=0.0, help_text='vector posicion Z')),
                ('xp', models.FloatField(default=0.0, help_text='vector velocidad X')),
                ('yp', models.FloatField(default=0.0, help_text='vector velocidad Y')),
                ('zp', models.FloatField(default=0.0, help_text='vector velocidad Z')),
                ('epoch', models.DateTimeField(auto_now_add=True)),
                ('referenceSystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ephems', to='CODS.ReferenceSystem')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ephems', to='GroundSegment.Satellite')),
            ],
        ),
    ]
