# Generated by Django 2.2 on 2019-05-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0002_auto_20181120_2212'),
        ('CODS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ephem',
            new_name='Ephemeride',
        ),
    ]
