# Generated by Django 2.2.1 on 2019-05-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CODS', '0002_auto_20190516_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ephemeride',
            name='epoch',
            field=models.DateTimeField(),
        ),
    ]
