# Generated by Django 2.2.1 on 2019-05-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CODS', '0003_auto_20190521_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='ephemeride',
            name='secondInEclipse',
            field=models.IntegerField(default=0, help_text='Segundos en eclipse, si no lo esta'),
        ),
    ]
