# Generated by Django 2.2.1 on 2019-05-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CODS', '0004_ephemeride_secondineclipse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ephemeride',
            old_name='secondInEclipse',
            new_name='secondsInEclipse',
        ),
    ]
