# Generated by Django 2.2.1 on 2019-05-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CODS', '0005_auto_20190529_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='ephemeride',
            name='eclipsed',
            field=models.BooleanField(default=False),
        ),
    ]
