# Generated by Django 2.2.2 on 2019-06-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CODS', '0006_ephemeride_eclipsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ephemeride',
            name='secondsInEclipse',
            field=models.IntegerField(help_text='Segundos en eclipse o tiempo restante para estarlo', null=True),
        ),
    ]
