# Generated by Django 4.0.6 on 2022-12-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WSClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4', models.CharField(default='', help_text='ipv4', max_length=24, verbose_name='Ipv4')),
                ('port', models.IntegerField(default=0, verbose_name='port')),
                ('lastConnection', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribedTlmyVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', help_text='var name satellite.tlmyvar', max_length=64, verbose_name='fullname')),
                ('wsClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribedTlmyVar', to='API.wsclient')),
            ],
        ),
    ]
