# Generated by Django 4.0.6 on 2023-02-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsclient',
            name='lastTlmyVarId',
            field=models.BigIntegerField(default=0),
        ),
    ]
