# Generated by Django 4.0.6 on 2023-02-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_wsclient_lasttlmyvarid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wsclient',
            name='lastTlmyVarId',
        ),
    ]
