# Generated by Django 4.0.6 on 2023-02-16 20:11

from django.db import migrations, models
import django.db.models.deletion


def clean_wsclients(apps, schema_editor):
    #remove wsclients and their susbcriptions by cascade
    apps.get_model('API', 'WSClient').objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0057_tlmyvar_rawvalue'),
        ('API', '0005_wsclient_lasttlmyvarid'),
    ]

    

    operations = [
        migrations.RunPython(clean_wsclients),

        migrations.AddField(
            model_name='subscribedtlmyvar',
            name='tlmyVarType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='Telemetry.tlmyvartype'),
        ),
    ]
