# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-12 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlmyvartype',
            name='maxValue',
            field=models.FloatField(default=1.7976931348623157e+308, verbose_name='Maximo valor tolerable'),
        ),
        migrations.AlterField(
            model_name='tlmyvartype',
            name='minValue',
            field=models.FloatField(default=2.2250738585072014e-308, verbose_name='Minimo valor tolerable'),
        ),
    ]
