# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-12 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0002_auto_20180612_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitofmeasurement',
            old_name='codigo',
            new_name='code',
        ),
    ]
