# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-13 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0001_initial'),
        ('Telemetry', '0004_tlmyrawdata_capturedat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tlmyrawdata',
            unique_together=set([('capturedAt', 'satellite')]),
        ),
    ]
