# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-28 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0005_auto_20180613_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlmyvar',
            name='calSValue',
            field=models.CharField(default=None, help_text='Valor como string de la variable de telemetria', max_length=128, verbose_name='Valor como string de la variable de telemetria'),
        ),
        migrations.AlterField(
            model_name='tlmyvartype',
            name='lastCalSValue',
            field=models.CharField(default='No defined', help_text='Valor como string de la variable de telemetria', max_length=128, null=True, verbose_name='Valor como string de la variable de telemetria'),
        ),
    ]
