# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-11 13:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0006_auto_20180628_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvartype',
            name='tstamp',
            field=models.DateTimeField(default=datetime.datetime(1976, 10, 30, 12, 0), verbose_name='Indica la fecha hora del dato suministrada por el equipo'),
        ),
        migrations.AlterField(
            model_name='tlmyvartype',
            name='lastUpdate',
            field=models.DateTimeField(null=True, verbose_name='Indica cuando se escribio la variable'),
        ),
    ]
