# Generated by Django 2.0.7 on 2018-07-18 17:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0007_auto_20180711_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyrawdata',
            name='payload',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='coefficient',
            name='tlmyVarType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coefficients', to='Telemetry.TlmyVarType'),
        ),
        migrations.AlterField(
            model_name='tlmyvar',
            name='tlmyVarType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tlmyVars', to='Telemetry.TlmyVarType'),
        ),
        migrations.AlterField(
            model_name='tlmyvartype',
            name='alarmType',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tmlyVarType', to='GroundSegment.Alarm'),
        ),
        migrations.AlterField(
            model_name='tlmyvartype',
            name='calibrationMethod',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tlmyVarTypes', to='Telemetry.Calibration'),
        ),
        migrations.AlterField(
            model_name='tlmyvartype',
            name='frameType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tlmyVarTypes', to='Telemetry.FrameType'),
        ),
        migrations.AlterField(
            model_name='tlmyvartype',
            name='tstamp',
            field=models.DateTimeField(default=datetime.datetime(1976, 10, 30, 12, 0, tzinfo=utc), verbose_name='Indica la fecha hora del dato suministrada por el equipo'),
        ),
        migrations.AlterField(
            model_name='tlmyvartype',
            name='unitOfMeasurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tlmyVarTypes', to='Telemetry.UnitOfMeasurement'),
        ),
    ]
