# Generated by Django 2.0.7 on 2018-07-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0008_auto_20180718_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyrawdata',
            name='strpayload',
            field=models.TextField(default='', verbose_name='Payload data in text format'),
        ),
    ]
