# Generated by Django 2.0.7 on 2018-09-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0009_tlmyrawdata_strpayload'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvar',
            name='UnixTimeStamp',
            field=models.BigIntegerField(default=0),
        ),
    ]
