# Generated by Django 2.0.7 on 2018-09-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0010_tlmyvar_unixtimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlmyvar',
            name='UnixTimeStamp',
            field=models.FloatField(default=0.0),
        ),
    ]
