# Generated by Django 2.0.7 on 2018-11-20 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0002_auto_20181120_2212'),
        ('Telemetry', '0011_auto_20180906_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvartype',
            name='subsystem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tlmyVarTypes', to='GroundSegment.SubSystem'),
        ),
        migrations.AlterField(
            model_name='tlmyvartype',
            name='varType',
            field=models.IntegerField(choices=[(0, 'integer'), (1, 'float'), (2, 'string'), (3, 'boolean')], default=0, verbose_name='Tipo de dato, 0=Integer, 1=Float, 2=String'),
        ),
    ]
