# Generated by Django 2.0.7 on 2019-02-14 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0013_auto_20190214_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='BLTlmyVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxIValue', models.IntegerField(default=0)),
                ('maxFValue', models.FloatField(default=0.0)),
                ('maxBValue', models.BooleanField(default=False)),
                ('maxSValue', models.CharField(default=None, help_text='Valor como string de la variable de telemetria', max_length=128, verbose_name='Valor como string de la variable de telemetria')),
                ('minIValue', models.IntegerField(default=0)),
                ('minFValue', models.FloatField(default=0.0)),
                ('minBValue', models.BooleanField(default=False)),
                ('minSValue', models.CharField(default=None, help_text='Valor como string de la variable de telemetria', max_length=128, verbose_name='Valor como string de la variable de telemetria')),
                ('avrIValue', models.IntegerField(default=0)),
                ('avrFValue', models.FloatField(default=0.0)),
                ('avrBValue', models.BooleanField(default=False)),
                ('avrSValue', models.CharField(default=None, help_text='Valor como string de la variable de telemetria', max_length=128, verbose_name='Valor como string de la variable de telemetria')),
                ('strDeviation', models.FloatField(default=0.0)),
                ('unixStartTime', models.FloatField(default=0.0)),
                ('unixEndTime', models.FloatField(default=0.0)),
                ('outlier', models.BooleanField(default=False, verbose_name='Valor erroneo')),
            ],
        ),
        migrations.CreateModel(
            name='BLTlmyVarL1',
            fields=[
                ('bltlmyvar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Telemetry.BLTlmyVar')),
                ('tlmyVarType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tlmyVarsL1', to='Telemetry.TlmyVarType')),
            ],
            bases=('Telemetry.bltlmyvar',),
        ),
        migrations.CreateModel(
            name='BLTlmyVarL2',
            fields=[
                ('bltlmyvar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Telemetry.BLTlmyVar')),
                ('tlmyVarType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tlmyVarsL2', to='Telemetry.TlmyVarType')),
            ],
            bases=('Telemetry.bltlmyvar',),
        ),
        migrations.CreateModel(
            name='BLTlmyVarL3',
            fields=[
                ('bltlmyvar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Telemetry.BLTlmyVar')),
                ('tlmyVarType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tlmyVarsL3', to='Telemetry.TlmyVarType')),
            ],
            bases=('Telemetry.bltlmyvar',),
        ),
        migrations.CreateModel(
            name='BLTlmyVarL4',
            fields=[
                ('bltlmyvar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Telemetry.BLTlmyVar')),
                ('tlmyVarType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tlmyVarsL4', to='Telemetry.TlmyVarType')),
            ],
            bases=('Telemetry.bltlmyvar',),
        ),
        migrations.CreateModel(
            name='BLTlmyVarL5',
            fields=[
                ('bltlmyvar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Telemetry.BLTlmyVar')),
                ('tlmyVarType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tlmyVarsL5', to='Telemetry.TlmyVarType')),
            ],
            bases=('Telemetry.bltlmyvar',),
        ),
    ]
