# Generated by Django 2.0.7 on 2019-02-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0014_bltlmyvar_bltlmyvarl1_bltlmyvarl2_bltlmyvarl3_bltlmyvarl4_bltlmyvarl5'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BLTlmyVarL1',
            new_name='TlmyVarL1',
        ),
        migrations.RenameModel(
            old_name='BLTlmyVarL2',
            new_name='TlmyVarL2',
        ),
        migrations.RenameModel(
            old_name='BLTlmyVarL3',
            new_name='TlmyVarL3',
        ),
        migrations.RenameModel(
            old_name='BLTlmyVarL4',
            new_name='TlmyVarL4',
        ),
        migrations.RenameModel(
            old_name='BLTlmyVarL5',
            new_name='TlmyVarL5',
        ),
    ]
