# Generated by Django 2.0.7 on 2019-02-14 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0015_auto_20190214_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='bltlmyvar',
            name='endTlmy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='endBLTmys', to='Telemetry.TlmyVar'),
        ),
        migrations.AddField(
            model_name='bltlmyvar',
            name='startTlmy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='startBLTlmys', to='Telemetry.TlmyVar'),
        ),
        migrations.AddField(
            model_name='tlmyvarlevel',
            name='lastDateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
