# Generated by Django 2.0.7 on 2019-02-15 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0002_auto_20181120_2212'),
        ('Telemetry', '0016_auto_20190214_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvarlevel',
            name='satellite',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='tlmyVarLevels', to='GroundSegment.Satellite'),
        ),
    ]
