# Generated by Django 2.0.7 on 2019-02-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0019_auto_20190215_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlmyvar',
            name='UnixTimeStamp',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
