# Generated by Django 2.0.7 on 2019-02-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0020_auto_20190215_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlmyrawdata',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='tlmyrawdata',
            name='strdata',
        ),
        migrations.RemoveField(
            model_name='tlmyrawdata',
            name='strpayload',
        ),
        migrations.AddField(
            model_name='tlmyrawdata',
            name='pylEnd',
            field=models.IntegerField(default=0, verbose_name='Fin del paquete de payload'),
        ),
        migrations.AddField(
            model_name='tlmyrawdata',
            name='pylStart',
            field=models.IntegerField(default=0, verbose_name='Inicio de paquete de payload'),
        ),
    ]
