# Generated by Django 2.0.7 on 2019-03-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0021_auto_20190228_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlmyvar',
            name='calIValue',
            field=models.BigIntegerField(default=0),
        ),
    ]
