# Generated by Django 2.2 on 2019-04-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0002_auto_20181120_2212'),
        ('Telemetry', '0022_auto_20190307_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlmyvarlevel',
            name='satellite',
        ),
        migrations.AddField(
            model_name='tlmyvarlevel',
            name='satellites',
            field=models.ManyToManyField(to='GroundSegment.Satellite'),
        ),
        migrations.AlterField(
            model_name='tlmyvarlevel',
            name='queryRange',
            field=models.IntegerField(default=0, verbose_name='Delta de tiempo (En horas?)a partir del cual aplica el nivel (Para la consulta)'),
        ),
    ]
