# Generated by Django 2.2 on 2019-04-30 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0002_auto_20181120_2212'),
        ('Telemetry', '0023_auto_20190430_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlmyvarlevel',
            name='lastDateTime',
        ),
        migrations.RemoveField(
            model_name='tlmyvarlevel',
            name='satellites',
        ),
        migrations.CreateModel(
            name='TlmyVarLevelSatellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastid', models.IntegerField(default=0)),
                ('lastDateTime', models.DateTimeField(null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SatelliteLevels', to='Telemetry.TlmyVarLevel')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TlmyLevels', to='GroundSegment.Satellite')),
            ],
        ),
    ]
