# Generated by Django 2.2 on 2019-05-09 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0024_auto_20190430_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvar',
            name='tlmyRawData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rawdata', to='Telemetry.TlmyRawData'),
        ),
        migrations.AlterField(
            model_name='tlmyvarlevelsatellite',
            name='lastDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
