# Generated by Django 2.2.1 on 2019-06-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0025_auto_20190509_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlmyvartype',
            name='maxValue',
        ),
        migrations.RemoveField(
            model_name='tlmyvartype',
            name='minValue',
        ),
    ]
