# Generated by Django 2.2.1 on 2019-06-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0026_auto_20190606_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvartype',
            name='maxValue',
            field=models.FloatField(null=True, verbose_name='Maximo valor tolerable'),
        ),
        migrations.AddField(
            model_name='tlmyvartype',
            name='minValue',
            field=models.FloatField(null=True, verbose_name='Minimo valor tolerable'),
        ),
    ]
