# Generated by Django 2.2.2 on 2019-06-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0029_predictiontype_tlmyprediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlmyprediction',
            name='tlmyVarType',
        ),
        migrations.RemoveField(
            model_name='tlmyprediction',
            name='type',
        ),
        migrations.DeleteModel(
            name='PredictionType',
        ),
        migrations.DeleteModel(
            name='TlmyPrediction',
        ),
    ]
