# Generated by Django 2.2.2 on 2019-06-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0031_predictiontype_tlmyprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictiontype',
            name='aClass',
            field=models.CharField(default='NoDef', max_length=512, verbose_name='Class Name (Library)'),
        ),
    ]
