# Generated by Django 2.2.2 on 2019-06-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0032_auto_20190613_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyprediction',
            name='std',
            field=models.FloatField(null=True, verbose_name='Standard deviation'),
        ),
    ]
