# Generated by Django 2.2.2 on 2019-06-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0033_tlmyprediction_std'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvar',
            name='calSPredictedValue',
            field=models.CharField(default=None, help_text='Valor predecido como string de la variable de telemetria', max_length=128, null=True, verbose_name='Valor predecido como string de la variable de telemetria'),
        ),
    ]
