# Generated by Django 2.2.2 on 2019-06-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0034_tlmyvar_calspredictedvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyprediction',
            name='genTime',
            field=models.FloatField(default=0, verbose_name='Calculate model time'),
        ),
        migrations.AddField(
            model_name='tlmyvar',
            name='predictedTime',
            field=models.FloatField(default=0, verbose_name='Time to calculate predicted value'),
        ),
    ]
