# Generated by Django 2.2.2 on 2019-06-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0035_auto_20190627_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlmyvar',
            name='predictedTime',
        ),
        migrations.AddField(
            model_name='tlmyvar',
            name='genTime',
            field=models.FloatField(default=0, verbose_name='Time to calculate the value'),
        ),
    ]
