# Generated by Django 2.2.2 on 2020-03-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0036_auto_20190627_1844'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tlmyvar',
            unique_together={('tlmyVarType', 'tstamp')},
        ),
    ]
