# Generated by Django 2.2.2 on 2020-03-11 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0039_tlmyvartype_frametype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyrawdata',
            name='frameType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raws', to='Telemetry.FrameType'),
        ),
    ]
