# Generated by Django 2.2.2 on 2020-03-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0040_tlmyrawdata_frametype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvartype',
            name='tag',
            field=models.CharField(help_text='Free Field', max_length=64, null=True, verbose_name='Free field for differents purpouses'),
        ),
    ]
