# Generated by Django 2.2.2 on 2020-04-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0041_tlmyvartype_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctype',
            name='tag',
            field=models.CharField(help_text='Free Field', max_length=64, null=True, verbose_name='Free field for differents purpouses'),
        ),
    ]
