# Generated by Django 2.2.2 on 2020-04-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0042_ctype_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlmyvarl1',
            name='bltlmyvar_ptr',
        ),
        migrations.RemoveField(
            model_name='tlmyvarl1',
            name='tlmyVarType',
        ),
        migrations.RemoveField(
            model_name='tlmyvarl2',
            name='bltlmyvar_ptr',
        ),
        migrations.RemoveField(
            model_name='tlmyvarl2',
            name='tlmyVarType',
        ),
        migrations.RemoveField(
            model_name='tlmyvarl3',
            name='bltlmyvar_ptr',
        ),
        migrations.RemoveField(
            model_name='tlmyvarl3',
            name='tlmyVarType',
        ),
        migrations.RemoveField(
            model_name='tlmyvarl4',
            name='bltlmyvar_ptr',
        ),
        migrations.RemoveField(
            model_name='tlmyvarl4',
            name='tlmyVarType',
        ),
        migrations.RemoveField(
            model_name='tlmyvarl5',
            name='bltlmyvar_ptr',
        ),
        migrations.RemoveField(
            model_name='tlmyvarl5',
            name='tlmyVarType',
        ),
        migrations.RemoveField(
            model_name='tlmyvarlevelsatellite',
            name='level',
        ),
        migrations.RemoveField(
            model_name='tlmyvarlevelsatellite',
            name='satellite',
        ),
        migrations.DeleteModel(
            name='BLTlmyVar',
        ),
        migrations.DeleteModel(
            name='TlmyVarL1',
        ),
        migrations.DeleteModel(
            name='TlmyVarL2',
        ),
        migrations.DeleteModel(
            name='TlmyVarL3',
        ),
        migrations.DeleteModel(
            name='TlmyVarL4',
        ),
        migrations.DeleteModel(
            name='TlmyVarL5',
        ),
        migrations.DeleteModel(
            name='TlmyVarLevel',
        ),
        migrations.DeleteModel(
            name='TlmyVarLevelSatellite',
        ),
    ]
