# Generated by Django 2.2.2 on 2020-05-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0043_auto_20200427_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlmyvar',
            name='calSPredictedValue',
            field=models.CharField(default=None, help_text='Valor predecido como string de la variable de telemetria', max_length=24, null=True, verbose_name='Valor predecido como string de la variable de telemetria'),
        ),
        migrations.AlterField(
            model_name='tlmyvar',
            name='calSValue',
            field=models.CharField(default=None, help_text='Valor como string de la variable de telemetria', max_length=24, verbose_name='Valor como string de la variable de telemetria'),
        ),
    ]
