# Generated by Django 2.2.2 on 2020-05-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0044_auto_20200502_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='TlmyVarInfo',
            fields=[
                ('calSPredictedValue', models.CharField(default=None, help_text='Valor predecido como string de la variable de telemetria', max_length=24, null=True, verbose_name='Valor predecido como string de la variable de telemetria')),
                ('genTime', models.FloatField(default=0, verbose_name='Time to calculate the value')),
                ('tlmyVar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to='Telemetry.TlmyVar')),
            ],
        ),
        migrations.RemoveField(
            model_name='tlmyvar',
            name='calSPredictedValue',
        ),
        migrations.RemoveField(
            model_name='tlmyvar',
            name='genTime',
        ),
    ]
