# Generated by Django 2.2.2 on 2020-05-02 20:08

from django.db import migrations, models

"""
ALTER TABLE "Telemetry_tlmyvar" ALTER COLUMN calSValue TYPE VARCHAR(12) USING SUBSTR(calSValue, 1, 12)
update "Telemetry_tlmyvar" set "calSValue" = SUBSTR("Telemetry_tlmyvar"."calSValue", 1, 12)
"""

class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0045_auto_20200502_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlmyvar',
            name='calSValue',
            field=models.CharField(default=None, help_text='Valor como string de la variable de telemetria', max_length=12, verbose_name='Valor como string de la variable de telemetria'),
        ),
    ]
