# Generated by Django 2.2.2 on 2020-07-15 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0006_auto_20200311_1824'),
        ('Telemetry', '0046_auto_20200502_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvar',
            name='satellite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tlmyvars', to='GroundSegment.Satellite'),
            preserve_default=False,
        ),
    ]
