# Generated by Django 2.2.2 on 2020-08-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0050_auto_20200819_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlmyvar',
            name='calSValue',
            field=models.CharField(default=None, help_text='Valor como string de la variable de telemetria', max_length=24, verbose_name='Valor como string de la variable de telemetria'),
        ),
    ]
