# Generated by Django 3.1.1 on 2020-10-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0052_auto_20200819_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvartype',
            name='checkoutlier',
            field=models.BooleanField(default=False, verbose_name='Check if outlier'),
        ),
        migrations.AddField(
            model_name='tlmyvartype',
            name='outliermaxlimit',
            field=models.BigIntegerField(default=0, verbose_name='Max outlier value'),
        ),
        migrations.AddField(
            model_name='tlmyvartype',
            name='outlierminlimit',
            field=models.BigIntegerField(default=0, verbose_name='Min outlier value'),
        ),
    ]
