# Generated by Django 4.0.3 on 2022-07-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0053_auto_20201026_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlmyvartype',
            name='varType',
        ),
        migrations.AddField(
            model_name='ctype',
            name='varType',
            field=models.IntegerField(choices=[(-1, 'other'), (0, 'integer'), (1, 'float'), (2, 'string'), (3, 'boolean')], default=0, verbose_name='Tipo de dato, -1=Otro 0=Integer, 1=Float, 2=String'),
        ),
    ]
