# Generated by Django 4.0.6 on 2022-10-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0054_remove_tlmyvartype_vartype_ctype_vartype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PacketType',
        ),
        migrations.RemoveField(
            model_name='tlmyvartype',
            name='lastCalBValue',
        ),
        migrations.RemoveField(
            model_name='tlmyvartype',
            name='lastCalFValue',
        ),
        migrations.RemoveField(
            model_name='tlmyvartype',
            name='lastCalIValue',
        ),
        migrations.RemoveField(
            model_name='tlmyvartype',
            name='lastCalSValue',
        ),
        migrations.RemoveField(
            model_name='tlmyvartype',
            name='lastRawValue',
        ),
        migrations.RemoveField(
            model_name='tlmyvartype',
            name='lastUpdate',
        ),
        migrations.RemoveField(
            model_name='tlmyvartype',
            name='tstamp',
        ),
    ]
