# Generated by Django 4.0.3 on 2022-10-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0055_delete_packettype_remove_tlmyvartype_lastcalbvalue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlmyvar',
            name='rawValue',
        ),
    ]
