# Generated by Django 4.0.3 on 2022-10-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0056_remove_tlmyvar_rawvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvar',
            name='rawValue',
            field=models.BinaryField(null=True),
        ),
    ]
