# Generated by Django 4.0.3 on 2023-02-17 18:35

from django.db import migrations, models

#python -m pip install -U Django => update to python 4.1 for async support

def fullname_update_v2(apps, schema_editor):
    #it could be replaced for a raw sql update
    tvts = apps.get_model('Telemetry', 'TlmyVar').objects.all().iterator(chunk_size=10000)
    for tv in tvts:
        tv.fullName = tv.tlmyVarType.fullName
        tv.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0058_tlmyvartype_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvar',
            name='fullName',
            field=models.CharField(default='', help_text='fullname', max_length=64, verbose_name='fullname'),
        ),
        migrations.RunPython(fullname_update_v2),
    ]
