# Generated by Django 4.1.7 on 2023-02-28 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0059_tlmyvar_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvartype',
            name='calSValue',
            field=models.CharField(help_text='Valor como string de la variable de telemetria', max_length=128, null=True, verbose_name='Valor como string de la variable de telemetria'),
        ),
        migrations.AddField(
            model_name='tlmyvartype',
            name='lastUpdate',
            field=models.DateTimeField(null=True, verbose_name='Indica cuando se escribio la variable'),
        ),
        migrations.AddField(
            model_name='tlmyvartype',
            name='tstamp',
            field=models.DateTimeField(default=datetime.datetime(1980, 1, 6, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='Indica la fecha hora del dato suministrada por el equipo'),
        ),
    ]
