# Generated by Django 4.1.7 on 2023-02-23 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0059_tlmyvar_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvartype',
            name='lastCalSValue',
            field=models.CharField(default='No defined', help_text='Valor como string de la variable de telemetria', max_length=128, null=True, verbose_name='Valor como string de la variable de telemetria'),
        ),
        migrations.AddField(
            model_name='tlmyvartype',
            name='lastTlmyVarId',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='tlmyvartype',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
