# Generated by Django 4.1.7 on 2023-02-24 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0060_tlmyvartype_lastcalsvalue_tlmyvartype_lasttlmyvarid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlmyvartype',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
