# Generated by Django 4.1.7 on 2023-02-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0060_tlmyvartype_calsvalue_tlmyvartype_lastupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvartype',
            name='lastUpdateTlmyVarId',
            field=models.BigIntegerField(null=True, verbose_name='pk related tlmyvar'),
        ),
    ]
