# Generated by Django 4.1.7 on 2023-03-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0060_tlmyvartype_unixtimestamp_tlmyvartype_calsvalue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlmyvartype',
            name='UnixTimeStamp',
        ),
        migrations.RemoveField(
            model_name='tlmyvartype',
            name='calSValue',
        ),
        migrations.RemoveField(
            model_name='tlmyvartype',
            name='lastUpdate',
        ),
        migrations.RemoveField(
            model_name='tlmyvartype',
            name='lastUpdateTlmyVarId',
        ),
    ]
