# Generated by Django 4.1.7 on 2023-02-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0061_tlmyvartype_lastupdatetlmyvarid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlmyvartype',
            name='lastUpdateTlmyVarId',
        ),
    ]
