# Generated by Django 4.1.7 on 2023-02-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetry', '0063_tlmyvartype_lastupdatetlmyvarid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlmyvartype',
            name='tstamp',
        ),
        migrations.AddField(
            model_name='tlmyvartype',
            name='UnixTimeStamp',
            field=models.FloatField(null=True, verbose_name='variable timestamp'),
        ),
    ]
