# Generated by Django 2.0.7 on 2019-03-07 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Telecommand', '0002_command_commandparameter_passscript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='commandType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='Telecommand.CommandType'),
        ),
        migrations.AlterField(
            model_name='command',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='GroundSegment.Satellite'),
        ),
        migrations.AlterField(
            model_name='commandtype',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandsType', to='GroundSegment.Satellite'),
        ),
        migrations.AlterField(
            model_name='passscript',
            name='apass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passScripts', to='GroundSegment.Pasada'),
        ),
        migrations.AlterField(
            model_name='passscript',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passScripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passscript',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passScripts', to='GroundSegment.Satellite'),
        ),
    ]
